require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

# Set this to the minimum supported ruby in the gemspec. Otherwise
# we get errors if our ruby version doesn't match.
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Turn off ABC metrics for the tests.
Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

# Turn block length metrics off for the tests and gemspec.
Metrics/BlockLength:
  Exclude:
    - 'rubyzip.gemspec'
    - 'test/**/*.rb'

# Turn class length metrics off for the tests.
Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

# Turn method length metrics off for the tests.
Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'
