# Copyright (c) 2002-2025, The Rubyzip Developers.
#
# Licensed under the BSD License. See LICENCE for details.

# This is the top-level Rubocop configuration for rubyzip v4+.

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

# When excluding files, use merge mode so we preserve default Rubocop config.
inherit_mode:
  merge:
    - Exclude

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 100

Lint/EmptyClass:
  Enabled: false

# Turn block length metrics off for the gemspec.
Metrics/BlockLength:
  Exclude:
    - 'rubyzip.gemspec'

Minitest/MultipleAssertions:
  Max: 5

# Set a consistent way of checking types.
Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/HashEachMethods:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets
